config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  root 'tests#index'

  get 'contact_us', to: 'guru_letters#new', as: 'new_guru_letter'
  post 'contact_us', to: 'guru_letters#create', as: 'create_guru_letter'

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: :index

  namespace :admin do
    root 'tests#index'
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < User
  validates :first_name, :last_name, presence: true
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :answers_limit, on: :create

  scope :correct_answer, -> { where(correct: true) }

  private

  def answers_limit
    errors.add(:limit, 'question must have 1 to 4 answers') if question.answers.count >= 4
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
# frozen_string_literal: true

class Badge < ApplicationRecord
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges
  validates :title, :img_url, :condition, :description, presence: true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  default_scope { order(title: :asc) }

  has_many :tests, dependent: :nullify

  validates :title, presence: true
end

app/models/gist.rb
# frozen_string_literal: true

class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
  validates :url, presence: true
end

app/models/guru_letter.rb
# frozen_string_literal: true

class GuruLetter
  include ActiveModel::Model

  EMAIL_FORMAT = /\A[^@\s]+@[^@\s]+\z/.freeze

  attr_accessor :name, :email, :message

  validates :name, :message, presence: true
  validates :email, format: EMAIL_FORMAT
end

app/models/join_user_test.rb
class JoinUserTest < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
# frozen_string_literal: true

class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  validates :title, presence: true
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :timer, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :title, uniqueness: { scope: :level }

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  scope :by_category,
        lambda { |category|
          joins(:category)
            .where('categories.title = ?', category)
        }
  scope :by_level,
        lambda { |level|
          where('level = ?', level)
        }

  def self.tests_by_category(category)
    by_category(category).order(id: :desc).pluck(:title)
  end

  def self.tests_by_level(level)
    by_level(level).pluck(:level)
  end
end

app/models/test_passage.rb
# frozen_string_literal: true

class TestPassage < ApplicationRecord
  SUCCESS = 85.0

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true
  has_many :badges

  before_save :before_save_set_next_question

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def completed?
    current_question.nil?
  end

  def test_result
    (correct_questions.to_f / test_questions_count * 100).round(1)
  end

  def test_passed?
    test_result >= SUCCESS
  end

  def current_question_number
    test.questions.order(:id).pluck(:id).index(current_question.id) + 1
  end

  def test_questions_count
    test.questions.count
  end

  def progress
    (current_question_number.to_f / test_questions_count * 100).round(1)
  end

  def time_left
    (time_limit - Time.current).to_i if time_limit
  end

  def abort_test
    self.current_question = nil
  end

  def time_is_up?
    time_left&.zero?
  end

  # def time_to_pass
  #  test.timer * 60 - time_left
  # end

  private

  def time_limit
    created_at + test.timer * 60 if test.timer.positive?
  end

  def before_save_set_next_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == Array(answer_ids).map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.where(correct: true)
  end

  def next_question
    if new_record?
      self.current_question = test.questions.first
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  EMAIL_FORMAT = /\A[^@\s]+@[^@\s]+\z/.freeze

  has_many :tests_by, class_name: 'Test', foreign_key: :author_id, dependent: :nullify
  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :gists, dependent: :destroy
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges

  scope :tests_by_level, ->(level) { where(level: level) }

  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
         :validatable, :confirmable

  def show_tests(level)
    tests.tests_by_level(level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test: test)
  end

  def admin?
    type == 'Admin'
  end
end

app/models/user_badge.rb
# frozen_string_literal: true

class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/tests_controller.rb
# frozen_string_literal: true

class TestsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :find_test, only: %i[start]
  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_test_not_found

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end

  def rescue_with_test_not_found
    render html: "Error: test with id: #{params[:id]} not found"
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def current_year
    Date.current.year
  end

  def project_repo(author, repo)
    "http://github.com/#{author}/#{repo}"
  end

  def flash_message(type, message)
    content_tag :p, message, class: "flash #{type}"
  end

  def flash_class(level)
    case level
    when 'notice' then 'alert alert-info'
    when 'success' then 'alert alert-success'
    when 'error' then 'alert alert-danger'
    when 'alert' then 'alert alert-warning'
    end
  end
end

app/helpers/badges_helper.rb
# frozen_string_literal: true

module BadgesHelper
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Create new #{question.test.title} question"
    else
      "Edit #{question.test.title} question"
    end
  end
end

app/helpers/test_passages_helper.rb
# frozen_string_literal: true

module TestPassagesHelper
  def test_summary_message(test)
    if test.test_passed?
      t('.success_message')
    else
      t('.failed_message')
    end
  end

  def test_summary_score_color(test)
    if test.test_passed?
      'passed'
    else
      'failed'
    end
  end
end

app/helpers/tests_helper.rb
# frozen_string_literal: true

module TestsHelper
end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-dark bg-primary">
  <%= link_to t('.test_guru'), admin_root_path, class: 'navbar-brand' %>
    <%= t('.admin_panel') %>
  <span class="navbar-text">
      <%= t('.welcome', username: current_user.username) %>
      | <%= link_to t('.logout'), destroy_user_session_path, method: :delete, data: { confirm: t('.logout_confirm') } %>
  </span>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin panel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'admin/nav' %>

  <%= render 'shared/flash' %>

  <%= yield %>

  <%= render 'shared/footer' %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/nav' %>

    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>

      <%= render 'shared/footer' %>

  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2>
      <%= t('.header', count: resource.errors.count) %>:
    </h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :div, message.html_safe, class: flash_class(key) %>
<% end %>

app/views/shared/_footer.html.erb
<blockquote class="blockquote text-center">
  <p>
    <%= link_to t('.contact_us'), new_guru_letter_path %>
  </p>
  <p class="mb0"> &copy; <%= current_year %>
    <%= link_to 'vsav', project_repo('vsav', 'test-guru') %>
    Test Guru - учебное приложение на RoR, позволяющее создавать и проходить различные тесты.</p>
  <p>
  <footer class="blockquote-footer"><%= link_to 'онлайн-школа Thinknetica', 'http://thinknetica.com' %></footer>
</blockquote>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to t('.test_guru'), root_path, class: 'navbar-brand' %>
  <span class="navbar-text">
    <% if user_signed_in? %>
      <%= t('.welcome', username: current_user.username) %>
      | <%= link_to t('.logout'), destroy_user_session_path, method: :delete, data: { confirm: t('.logout_confirm') } %>
    <% else %>
      <%= link_to t('.login'), new_user_session_path %> |
      <%= link_to t('.register'), new_user_registration_path %>
    <% end %>
  </span>
</nav>