config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  root 'tests#index'

  get 'contact_us', to: 'guru_letters#new', as: 'new_guru_letter'
  post 'contact_us', to: 'guru_letters#create', as: 'create_guru_letter'

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: :index

  namespace :admin do
    root 'tests#index'
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
# frozen_string_literal: true

class TestPassage < ApplicationRecord
  SUCCESS = 85.0

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true
  has_many :badges

  before_save :before_save_set_next_question

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def completed?
    current_question.nil?
  end

  def test_result
    (correct_questions.to_f / test_questions_count * 100).round(1)
  end

  def test_passed?
    test_result >= SUCCESS
  end

  def current_question_number
    test.questions.order(:id).pluck(:id).index(current_question.id) + 1
  end

  def test_questions_count
    test.questions.count
  end

  def progress
    (current_question_number.to_f / test_questions_count * 100).round(1)
  end

  def time_left
    (time_limit - Time.current).to_i if time_limit
  end

  def abort_test
    self.current_question = nil
  end

  def time_is_up?
    time_left&.zero?
  end

  # def time_to_pass
  #  test.timer * 60 - time_left
  # end

  private

  def time_limit
    created_at + test.timer * 60 if test.timer.positive?
  end

  def before_save_set_next_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == Array(answer_ids).map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.where(correct: true)
  end

  def next_question
    if new_record?
      self.current_question = test.questions.first
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end
end

app/controllers/test_passages_controller.rb
# frozen_string_literal: true

class TestPassagesController < ApplicationController
  before_action :set_test_passage, only: %i[show update result gist]

  def show; end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])
    @test_passage.abort_test if @test_passage.time_is_up?
    if @test_passage.completed?
      award_user(@test_passage)
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render 'show'
    end
  end

  def gist
    result = GistQuestionService.new(@test_passage.current_question).call
    @gist = Gist.new(question: @test_passage.current_question,
                     user: @test_passage.user, url: result[:html_url])

    if @gist.save!
      flash[:notice] = t('.success', url: (helpers.link_to t('.view_gist'), @gist.url,
                                                           target: '_blank'))
    else
      flash[:alert] = t('.failure')
    end
    redirect_to @test_passage
  end

  private

  def award_user(test_passage)
    award = BadgeAwardService.new(test_passage).call
    current_user.badges.push(award)
  end

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
# frozen_string_literal: true

module TestPassagesHelper
  def test_summary_message(test)
    if test.test_passed?
      t('.success_message')
    else
      t('.failed_message')
    end
  end

  def test_summary_score_color(test)
    if test.test_passed?
      'passed'
    else
      'failed'
    end
  end
end

app/views/test_passages/result.html.erb
<h1><%= t'.header', title: @test_passage.test.title %></h1>


<p>
  <%= t('.result_correct_answers', correct: @test_passage.correct_questions, total: @test_passage.test_questions_count ) %>
</p>

<!--<p>
  <%#= t('.time_to_pass', time: @test_passage.time_to_pass) %>
</p>-->

<p>
  <%= test_summary_message(@test_passage) %>
  <span class=<%= test_summary_score_color(@test_passage) %>> <%= @test_passage.test_result %>%</span>
</p>

<div class="row">
    <%= render @test_passage.user.badges %>
</div>
<%= link_to t('test_passages.show.back_to_tests_link'), tests_path %>

app/views/test_passages/show.html.erb
<h1><%= t('.header', title: @test_passage.test.title ) %></h1>
<h2><%= t('.question_number', current: @test_passage.current_question_number, total: @test_passage.test_questions_count ) %></h2>
<% if @test_passage.test.timer %>
  <%= content_tag :div,'', class: 'timer display-4', data: { test_timer: @test_passage.time_left } %>
<% end %>

<p>
  <strong> <%= @test_passage.current_question.body %> </strong>
</p>
<div class="progress">
  <%= content_tag :div, t('.progress'), class: 'progress-bar progress-bar-striped progress-bar-animated',
                  role: 'progressbar',
                  data: { progress: @test_passage.progress } %>
</div>
<%= form_with url: test_passage_path(@test_passage), class: 'test_passage', local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
    <% end %>
  <p>
    <%= link_to 'Gist question', gist_test_passage_path(@test_passage), method: :post %>
  </p>
  <p>
    <%= form.submit t('.confirm') %>
  </p>
<% end %>

<%= link_to t('.back_to_tests_link'), tests_path %>