config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  root 'tests#index'

  get 'contact_us', to: 'guru_letters#new', as: 'new_guru_letter'
  post 'contact_us', to: 'guru_letters#create', as: 'create_guru_letter'

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: :index

  namespace :admin do
    root 'tests#index'
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :answers_limit, on: :create

  scope :correct_answer, -> { where(correct: true) }

  private

  def answers_limit
    errors.add(:limit, 'question must have 1 to 4 answers') if question.answers.count >= 4
  end
end

app/controllers/admin/answers_controller.rb
# frozen_string_literal: true

class Admin::AnswersController < Admin::BaseController
  before_action :find_question, only: %i[new create]
  before_action :set_answer, only: %i[show edit update destroy]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)
    if @answer.save
      redirect_to admin_question_path(@answer.question)
    else
      render 'new'
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_question_path(@answer.question)
    else
      render 'edit'
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question)
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<div class="card-body">
  <p class=<%= answer.correct? ? "text-success" : "card-text"%>>
    <%= answer.body %>
    <% if answer.correct? %>
      (correct)
    <% end %>
  </p>
  <div class="btn-group" role="group" aria-label="actions">
    <%= link_to 'Show', admin_answer_path(answer), class: 'btn btn-outline-secondary' %>
    <%= link_to 'Edit', edit_admin_answer_path(answer), class: 'btn btn-outline-secondary' %>
    <%= link_to 'Delete', admin_answer_path(answer), class: 'btn btn-outline-secondary',
                method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, id: :answer_body, rows:7, cols: 50 %>
  </p>

  <p>
    <%= form.label :correct %>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>

  <p><%= form.submit %></p>

<% end %>

app/views/admin/answers/edit.html.erb
<div class="container">
  <h1>Edit Answer</h1>

  <p>
    <%= @answer.question.body %>
  </p>

  <%= render 'form' %>
  <%= link_to 'Back', admin_question_path(@answer.question) %>
</div>

app/views/admin/answers/new.html.erb
<div class="container">
  <h1>New Answer</h1>

  <p>
    Question: <%= @question.body %>
  </p>

  <%= render 'form' %>
  <%= link_to 'Back', admin_question_path(@question) %>
</div>

app/views/admin/answers/show.html.erb
<h1>Question</h1>

<p>
  <%= @answer.question.body %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @answer.body %>
</p>

<p>
  <strong>Correct:</strong>
  <%= @answer.correct %>
</p>

<%= link_to 'Back', admin_question_path(@answer.question) %>