config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  root 'tests#index'

  get 'contact_us', to: 'guru_letters#new', as: 'new_guru_letter'
  post 'contact_us', to: 'guru_letters#create', as: 'create_guru_letter'

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: :index

  namespace :admin do
    root 'tests#index'
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
# frozen_string_literal: true

class Admin::QuestionsController < Admin::BaseController
  before_action :find_test, only: %i[index new create]
  before_action :find_question, only: %i[show edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def show; end

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to admin_test_path(@question.test)
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to admin_test_path(@question.test)
    else
      render 'edit'
    end
  end

  def destroy
    @question.destroy
    redirect_to admin_test_path(@question.test)
  end

  private

  def question_params
    params.require(:question).permit(:body)
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def rescue_with_question_not_found
    render html: "Error: question with id: #{params[:id]} not found"
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Create new #{question.test.title} question"
    else
      "Edit #{question.test.title} question"
    end
  end
end

app/views/admin/questions/_form.html.erb
<h1><%= question_header(@question) %></h1>

<%= form_with model: [:admin, @test, @question], local: true do |form| %>

  <%= render 'shared/errors', resource: @question %>

  <p>
    <%= form.label :body %>
    <%= form.text_field :body, id: :question_body, size: 50 %>
  </p>

  <p><%= form.submit %></p>

<%end %>

app/views/admin/questions/_question.html.erb
<div class="card-body">
  <p class="card-text">
    <%= question.body %>
  </p>
  <div class="btn-group" role="group" aria-label="actions">
    <%= link_to 'Show', admin_question_path(question), class: 'btn btn-outline-secondary' %>
    <%= link_to 'Edit', edit_admin_question_path(question), class: 'btn btn-outline-secondary' %>
    <%= link_to 'Delete', admin_question_path(question), class: 'btn btn-outline-secondary',
                          method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/admin/questions/edit.html.erb
<div class="container">
  <%= render 'form' %>

  <p> <%= link_to 'Back to test questions list', admin_test_path(@question.test) %></p>
</div>

app/views/admin/questions/new.html.erb
<div class="container">
  <%= render 'form' %>

  <p> <%= link_to 'Back to test questions list', admin_test_path(@question.test) %></p>
</div>

app/views/admin/questions/show.html.erb
<div class="container">
  <h1><%= @question.test.title %> Question</h1>
  <p><%= @question.body %></p>

  <h2>Answers</h2>

  <%= render @question.answers %>

  <p> <%= link_to 'New answer', new_admin_question_answer_path(@question) %> </p>
  <p> <%= link_to 'Edit question', edit_admin_question_path(@question) %> </p>
  <p> <%= link_to 'Back to test questions list', admin_test_path(@question.test) %> </p>

</div>